version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: productuser
      POSTGRES_DB: product_info
    ports:
      - "5433:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:


