name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: product_user
          POSTGRES_PASSWORD: productuser
          POSTGRES_DB: product_info
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Maven Install
        run: mvn clean install -DskipTests=true

      - name: Save to Cache
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run Tests
        run: mvn test



